DOANno1/DOANno1/DOANno1/Controllers/ChamCongController.cs
using DOANno1.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOANno1.Controllers
{
    public class ChamCongController : Controller
    {
        public DataClasses1DataContext db = new DataClasses1DataContext();


        public ActionResult QuanLyChamCong()
        {
            if (Shared.Utils.check_login(Session))
            {
                // Lấy danh sách tất cả nhân viên từ CSDL
                var nhanVienList = db.NhanViens.ToList();

                if (nhanVienList != null)
                {
                    ViewBag.NhanVienList = nhanVienList;
                }

                // Lấy danh sách chấm công của nhân viên hiện tại
                string maNhanVien = Session["MaNV"] as string;
                var chamCongList = db.QLChamCongs
                    .Where(cc => cc.MaNV == maNhanVien)
                    .Select(cc => cc.SBChamCong.HasValue ? cc.SBChamCong.Value.Date : (DateTime?)null)
                    .ToList();

                if (chamCongList != null)
                {
                    ViewBag.ChamCongList = JsonConvert.SerializeObject(chamCongList); // Chuyển thành chuỗi JSON
                }

                return View();
            }

            return RedirectToAction("DangNhap", "TaiKhoan");
        }



        public ActionResult ql_chamcong()
        {
            if (Shared.Utils.check_login(Session))
            {
                string maNhanVien = Session["MaNV"] as string;

                // Lấy thông tin nhân viên từ CSDL dựa trên mã nhân viên
                var nhanVien = db.NhanViens.FirstOrDefault(nv => nv.MaNV == maNhanVien);

                if (nhanVien != null)
                {
                    ViewBag.tenNhanVien = nhanVien.HoTenNV;
                }
                var chamCongList = db.QLChamCongs
                           .Select(cc => cc.SBChamCong.HasValue ? cc.SBChamCong.Value.Date : (DateTime?)null)
                           .ToList();


                if (chamCongList != null)
                {
                    ViewBag.ChamCongList = JsonConvert.SerializeObject(chamCongList); // Chuyển thành chuỗi JSON
                }

                return View();
            }

            return RedirectToAction("DangNhap", "TaiKhoan");
        }
        [HttpPost]
        public ActionResult LuuChamCong(string maNhanVien, string SBChamCong)
        {
            ChamCongModel result = new ChamCongModel();

            try
            {
                if (DateTime.TryParse(SBChamCong, out DateTime thoiGianChamCong))
                {
                    // Kiểm tra xem đã chấm công cho ngày này chưa
                    var existingAttendance = db.QLChamCongs
                        .FirstOrDefault(cc => cc.MaNV == maNhanVien && cc.SBChamCong.HasValue && cc.SBChamCong.Value.Date == thoiGianChamCong.Date);

                    if (existingAttendance != null)
                    {
                        // Thay đổi màu sắc của ngày đã chấm công sang màu xanh
                        result.LuuThanhCong = false;
                        result.Loi = "Ngày đã chấm công trước đó.";
                    }
                    else
                    {
                        // Tạo đối tượng chấm công mới
                        QLChamCong newChamCong = new QLChamCong
                        {
                            MaCC = Guid.NewGuid().ToString().Substring(0, 10),
                            MaNV = maNhanVien,
                            SBChamCong = thoiGianChamCong
                        };

                        // Chèn thông tin chấm công vào CSDL
                        db.QLChamCongs.InsertOnSubmit(newChamCong);
                        db.SubmitChanges();

                        result.LuuThanhCong = true;
                    }
                }
                else
                {
                    result.LuuThanhCong = false;
                    result.Loi = "Ngày chấm công không hợp lệ.";
                }
            }
            catch (Exception ex)
            {
                result.LuuThanhCong = false;
                result.Loi = "Lỗi khi lưu chấm công: " + ex.Message;
            }

            return Json(result);
        }


    }

}

DOANno1/DOANno1/DOANno1/Controllers/ChartController.cs
using System;
using DOANno1.Models;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOANno1.Controllers
{
    public class ChartController : Controller
    {
        //public DataClasses1DataContext db = new DataClasses1DataContext();
        public ActionResult GetAttendanceData(int year)
        {
            using (DataClasses1DataContext db = new DataClasses1DataContext())
            {
                var data = (from cc in db.QLChamCongs
                            where cc.NamCC == year
                            group cc by cc.ThangCC into g
                            select new
                            {
                                ThangCC = g.Key,
                                SoLuongNhanVien = g.Count()
                            }).OrderBy(x => x.ThangCC).ToList();

                return Json(data, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetYears()
        {
            DataClasses1DataContext db = new DataClasses1DataContext();
            var years = db.QLChamCongs.Select(c => c.NamCC).Distinct().ToList();
            return Json(years, JsonRequestBehavior.AllowGet);
        }
    }
}

DOANno1/DOANno1/DOANno1/Controllers/HomeController.cs
using DOANno1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOANno1.Controllers
{
    public class HomeController : Controller
    {
        public DataClasses1DataContext dbo = new DataClasses1DataContext();

        public ActionResult Index()
        {
            if (System.Web.HttpContext.Current.Session["is_login"] != null)
            {
                if ((bool)Session["is_login"])
                {
                    //trường hợp đã login rồi
                    return View();
                }
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }

        public ActionResult Index2()
        {
            if (Shared.Utils.check_login(Session))
            {
                return View();
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult ql_chucvu()
        {
            if (Shared.Utils.check_login(Session))
            {
                return View();
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }

        public ActionResult LogoutConfirmation()
        {
            string script = "if(confirm('Bạn có chắc chắn muốn đăng xuất?')){ window.location.href = '" + Url.Action("DangNhap", "TaiKhoan") + "'; }";
            return JavaScript(script);
        }
        public ActionResult Users()
        {
            if (System.Web.HttpContext.Current.Session["is_login"] != null)
            {
                if ((bool)Session["is_login"])
                {
                    return View();
                }
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }

    }
}

DOANno1/DOANno1/DOANno1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

DOANno1/DOANno1/DOANno1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

DOANno1/DOANno1/DOANno1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <select id="select" class="form-control" style="width: 150px;">
        </select>
        <div>
            <canvas style="height:150px;" id="employeeAttendanceChart"></canvas>
        </div>
    </div>
</div>

@section scripts{
    <script>
        var ctx = document.getElementById('employeeAttendanceChart');

        $(document).ready(function () {
            $.ajax({
                url: '@Url.Action("GetYears", "Chart")',
                type: 'GET',
                success: function (data) {
                    var select = $('#select');
                    select.empty();
                    select.append('<option value="0">Select Year</option>');
                    $.each(data, function (index, item) {
                        select.append($('<option></option>').val(item).html(item));
                    });
                }
            });

            $('#select').change(function () {
                var selectedYear = $(this).val(); // Lấy giá trị năm từ thẻ select khi có sự kiện change

                $.ajax({
                    url: '@Url.Action("GetAttendanceData", "Chart")',
                    type: 'GET',
                    data: { year: selectedYear }, // Sử dụng giá trị năm đã chọn
                    success: function (data) {
                        var months = [];
                        var counts = [];

                        data.forEach(function(item) {
                            months.push(item.ThangCC);
                            counts.push(item.SoLuongNhanVien);
                        });

                        var barChartData = {
                            labels: months,
                            datasets: [{
                                label: 'Số lượng nhân viên',
                                backgroundColor: 'green',
                                borderWidth: 1,
                                data: counts
                            }]
                        };

                        var myBarChart = new Chart(ctx, {
                            type: "bar",
                            data: barChartData,
                            options: {
                                scales: {
                                    y: {
                                        ticks: {
                                            beginAtZero: false,
                                            suggestedMin: 1
                                        }
                                    }
                                }
                            }
                        });
                    }
                });
            });
        });

    </script>
}

DOANno1/DOANno1/DOANno1/Views/Home/Index2.cshtml
@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Home/Users.cshtml";
}

DOANno1/DOANno1/DOANno1/Views/Home/Users.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Quản lý nhân viên</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../Content/images/favicon.png">
    <link rel="stylesheet" href="../Content/vendor/owl-carousel/css/owl.carousel.min.css">
    <link rel="stylesheet" href="../Content/vendor/owl-carousel/css/owl.theme.default.min.css">
    <link href="../Content/vendor/jqvmap/css/jqvmap.min.css" rel="stylesheet">
    <link href="../Content/css/style.css" rel="stylesheet">

    <!--flot-chart js-->
    @*<script src="../Content/vendor/flot/jquery.flot.js"></script>
        <script src="../Content/vendor/flot/jquery.flot.resize.js"></script>*@

    @*<script src="../Content/vendor/jqvmap/js/jquery.vmap.min.js"></script>
        <script src="../Content/vendor/jqvmap/js/jquery.vmap.usa.js"></script>*@
    @*<script src="../Content/vendor/jquery.counterup/jquery.counterup.min.js"></script>*@

    <!--Required vendors-->
    <script src="../Content/vendor/global/global.min.js"></script>
    @*<script src="../Scripts/js/quixnav-init.js"></script>
        <script src="../Scripts/js/custom.min.js"></script>*@

    <link rel="stylesheet" href="../Content/Site.css" />


</head>
<body>
    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <a href="/Home/Index" class="brand-logo">
                <img class="logo-abbr" src="../Content/images/logo.png" alt="">
                <img class="logo-compact" src="../Content/images/logo-text.png" alt="">
                <img class="brand-title" src="../Content/images/logo-text.png" alt="">
            </a>

            <div class="nav-control">
                <div class="hamburger">
                    <span class="line"></span><span class="line"></span><span class="line"></span>
                </div>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->
        <!--**********************************
            Header start
        ***********************************-->
        <div class="header">
            <div class="header-content">
                <nav class="navbar navbar-expand">
                    <div class="collapse navbar-collapse justify-content-between">
                        <div class="navbar-nav header-right">
                            <div class="nav-item dropdown header-profile">
                                <a class="nav-link" href="#" role="button" data-toggle="dropdown">
                                    <i class="mdi mdi-account"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="javascript:void(0);" onclick="return logoutConfirmation();" class="dropdown-item">
                                        <i class="icon-key"></i>
                                        <span class="ml-2">Logout</span>
                                    </a>

                                    <script>
                                        function logoutConfirmation() {
                                            if (confirm('Bạn có chắc chắn muốn đăng xuất?')) {
                                                 window.location.href = '@Url.Action("Logout", "TaiKhoan")';
                                            }
                                            return false;
                                        }
                                    </script>
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->
        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="quixnav">
            <div class="quixnav-scroll">
                <ul class="metismenu" id="menu">
                    <li>
                        <a href="@Url.Action("ql_chamcong", "ChamCong")" aria-expanded="false">
                            <i class="icon icon-globe-2"></i><span class="nav-text">Chấm công</span>
                        </a>
                    </li>
                </ul>
            </div>


        </div>
        <!--**********************************
            Sidebar end
        ***********************************-->
        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">
            @RenderBody()
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        <!--**********************************
            Footer start
        ***********************************-->
        <!--**********************************
            Footer end
        ***********************************-->
        <!--**********************************
           Support ticket button start
        ***********************************-->
        <!--**********************************
           Support ticket button end
        ***********************************-->


    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->
    <!--**********************************
        Scripts
    ***********************************-->
    <!--Required vendors-->
    @*<script src="../Content/vendor/global/global.min.js"></script>*@
    <script src="../Scripts/js/quixnav-init.js"></script>
    <script src="../Scripts/js/custom.min.js"></script>
    <!--Vectormap-->
    <script src="../Content/vendor/raphael/raphael.min.js"></script>
    <script src="../Content/vendor/morris/morris.min.js"></script>


    <script src="../Content/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="../Content/vendor/chart.js/Chart.bundle.min.js"></script>
    <script src="../Content/vendor/gaugeJS/dist/gauge.min.js"></script>
    <!--flot-chart js-->
    <!--<script src="../Content/vendor/flot/jquery.flot.js"></script>
    <script src="../Content/vendor/flot/jquery.flot.resize.js"></script>-->
    <!--Owl Carousel-->
    <script src="../Content/vendor/owl-carousel/js/owl.carousel.min.js"></script>

    <!--Counter Up-->
    @*<script src="../Content/vendor/jqvmap/js/jquery.vmap.min.js"></script>
        <script src="../Content/vendor/jqvmap/js/jquery.vmap.usa.js"></script>
        <script src="../Content/vendor/jquery.counterup/jquery.counterup.min.js"></script>*@
    @*<script src="../Scripts/js/dashboard/dashboard-1.js"></script>
        <script src="../Scripts/js/dashboard/dashboard-1.js"></script>*@
    @RenderSection("scripts", false)
</body>
</html>