DOANno1/DOANno1/DOANno1/Controllers/QLTKController.cs
using DOANno1.Models;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace DOANno1.Controllers
{
    public class QLTKController : Controller
    {
        public DataClasses1DataContext db = new DataClasses1DataContext();
        // GET: QLTK
        public ActionResult Index()
        {
            if (DOANno1.Shared.Utils.check_login(Session))
            {
                return View();
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }
        public ActionResult ThemTK()
        {
            if (DOANno1.Shared.Utils.check_login(Session))
            {
                return View();
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }

        public ActionResult SuaTK()
        {
            if (DOANno1.Shared.Utils.check_login(Session))
            {
                return View();
            }
            return RedirectToAction("DangNhap", "TaiKhoan");
        }

        //[HttpPost]
        public string Them()
        {
            string tenTK = Request["txt_tentk"];
            string user = Request["txt_user"];
            string password = Request["txt_password"];
            string quyenTC = Request["txt_quyentc"];
            /*string maNV = Request["txt_manv"];*/

            // Validate input
            if (!string.IsNullOrEmpty(tenTK) && !string.IsNullOrEmpty(user) &&
                !string.IsNullOrEmpty(password) && !string.IsNullOrEmpty(quyenTC) /*&&
                !string.IsNullOrEmpty(maNV)*/)
            {
                try
                {
                    // Check if both username and password already exist
                    if (db.Taikhoans.Any(o => o.User == user))
                    {
                        return "Tên người dùng đã tồn tại. Vui lòng chọn tên người dùng khác.";
                    }

                    // Insert new NhanVien object
                    Taikhoan tk = new Taikhoan();
                    tk.TenTK = tenTK;
                    tk.User = user;
                    tk.Password = password;
                    tk.QuyenTC = quyenTC;
                    /*tk.MaNV = maNV;*/

                    db.Taikhoans.InsertOnSubmit(tk);
                    db.SubmitChanges();

                    return "Thêm mới tài khoản thành công";
                }
                catch (Exception ex)
                {
                    return "Thêm mới tài khoản thất bại. Chi tiết lỗi: " + ex.Message;
                }
            }
            else
            {
                return "Vui lòng điền đầy đủ thông tin";
            }
        }


        //[HttpPost]
        //Sửa tài khoản
        public string get_TK_Info()
        {
            string tenTK = Request["tenTK"];

            //validate input
            if (!string.IsNullOrEmpty(tenTK))
            {
                try
                {
                    //trường hợp lấy được mssv từ trang suaSV
                    var qr = db.Taikhoans.Where(o => o.TenTK == tenTK);
                    if (qr.Any())
                    {
                        //trường hợp có dữ liệu trả về - tìm thấy sv có mssv theo yêu cầu
                        var tk_obj = qr.SingleOrDefault();

                        return JsonConvert.SerializeObject(tk_obj);
                    }
                    else
                    {
                        return "Không tìm thấy tài khoản có tên tài khoản =" + tenTK;
                    }

                }
                catch (Exception ex)
                {
                    return "Lấy thông tin tài khoản thất bại. Chi tiết lỗi: " + ex.Message;
                }
                //ok
                //return "MSSV: " + mssv + "; Họ tên: " + hoten + "; Mật khẩu: " + mk;

            }
            else
            {
                return "Vui lòng chọn tài khoản để chỉnh sửa";
            }
        }
        //[HttpPost]
        public string get_TK_Edit()
        {
            string tenTK = Request["tenTK"];

            //validate input
            if (!string.IsNullOrEmpty(tenTK))
            {
                try
                {
                    //trường hợp muốn update
                    var qrs = db.Taikhoans.Where(o => o.TenTK == tenTK);
                    if (qrs.Any())
                    {
                        //có trả về bản ghi.
                        Taikhoan tk = qrs.SingleOrDefault();

                        return JsonConvert.SerializeObject(tk);
                    }
                    else
                    {
                        return "Không tìm thấy tài khoản có mã tài khoản = " + tenTK;
                    }
                }
                catch (Exception ex)
                {
                    return "Cập nhật thông tin tài khoản thất bại. Chi tiết lỗi: " + ex.Message;
                }
            }
            else
            {
                return "Tên tài khoản không tồn tại";
            }
        }
        //[HttpPost]
        public string Edit()
        {
            //ví dụ về linq to sql
            //var qr = db.tbl_SVs; //select * from tbl_SV
            //var qr1 = db.tbl_SVs.Where(o => o.MSSV == "1234"); //select * from tbl_SV where mssv == "1234"
            string id = Request["txt_tentk"];
            string tenTK = Request["txt_tentk"];
            string user = Request["txt_user"];
            string password = Request["txt_password"];
            string quyenTC = Request["txt_quyentc"];
            /*string maNV = Request["txt_manv"];*/

            //validate input
            if (/*!string.IsNullOrEmpty(maNV) &&*/ !string.IsNullOrEmpty(tenTK) &&
                !string.IsNullOrEmpty(user) && !string.IsNullOrEmpty(password) &&
                !string.IsNullOrEmpty(quyenTC))
            {
                try
                {
                    //trường hợp muốn update
                    var qrs = db.Taikhoans.Where(o => o.TenTK == tenTK);
                    if (qrs.Any())
                    {
                        //có trả về bản ghi.
                        Taikhoan tk = qrs.SingleOrDefault();
                        tk.User = user;
                        tk.Password = password;
                        tk.QuyenTC = quyenTC;
                        /*tk.MaNV = maNV;*/

                        db.SubmitChanges();
                        JsonConvert.SerializeObject(tk);
                        return "Cập nhật thông tin tài khoản thành công";

                    }
                    else
                    {
                        return "Không tìm thấy tài khoản có mã tài khoản = " + tenTK;
                    }
                }
                catch (Exception ex)
                {
                    return "Cập nhật thông tin tài khoản thất bại. Chi tiết lỗi: " + ex.Message;
                }


            }
            else
            {
                //trường hợp mssv đã bị sửa
                return "Tên tài khoản không khớp với dữ liệu trong CSDL";
            }
        }




        //Hiện danh sách tài khoản
        public string get_All()
        {
            APIResult_ett<List<object>> rs = new APIResult_ett<List<object>>();
            try
            {
                var qr = db.Taikhoans.Where(o => o.isDetele == null || o.isDetele == 0)

                .Select(tk => new
                {
                    tk.TenTK,
                    tk.User,
                    tk.Password,
                    tk.QuyenTC,
                    /*tk.MaNV*/

                });

                if (qr.Any())
                {
                    rs.ErrCode = EnumErrCode.Success;
                    rs.ErrDesc = "Lấy danh sách tài khoản thành công";
                    rs.Data = qr.ToList<object>();
                }
                else
                {
                    rs.ErrCode = EnumErrCode.Empty;
                    rs.ErrDesc = "DSCV rỗng";
                    rs.Data = null;
                }
            }
            catch (Exception ex)
            {
                rs.ErrCode = EnumErrCode.Error;
                rs.ErrDesc = "Có lỗi xảy ra trong quá trình lấy về danh sách tài khoản. Chi tiết lỗi: " + ex.Message;
                rs.Data = null;
            }

            return JsonConvert.SerializeObject(rs);
        }

        //TÌm kiếm tài khoản
        public string Search_TK()
        {
            APIResult_ett<List<object>> rs = new APIResult_ett<List<object>>();
            try
            {
                string search_val = Request["search_val"];
                string search_type = Request["search_type"];

                if (!string.IsNullOrEmpty(search_val) && !string.IsNullOrEmpty(search_type))
                {
                    //truy vấn db để lấy toàn bộ dữ liệu về ds sinh viên
                    IQueryable<Taikhoan> qr = null;

                    switch (search_type)
                    {
                        case "TenTK":
                            qr = db.Taikhoans.Where(o => o.TenTK == search_val && (o.isDetele == null || o.isDetele == 0));
                            break;
                        case "User":
                            qr = db.Taikhoans.Where(o => o.User.Contains(search_val) && (o.isDetele == null || o.isDetele == 0));
                            break;
                        case "QuyenTC":
                            qr = db.Taikhoans.Where(o => o.QuyenTC.Contains(search_val) && (o.isDetele == null || o.isDetele == 0));
                            break;
                        default:
                            break;
                    }

                    if (qr.Any())
                    {
                        //có dữ liệu => chính là dssv
                        rs.ErrCode = EnumErrCode.Success;
                        rs.ErrDesc = "Tìm kiếm tài khoản thành công";

DOANno1/DOANno1/DOANno1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Quản lý nhân viên</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../Content/images/favicon.png">
    <link rel="stylesheet" href="../Content/vendor/owl-carousel/css/owl.carousel.min.css">
    <link rel="stylesheet" href="../Content/vendor/owl-carousel/css/owl.theme.default.min.css">
    <link href="../Content/vendor/jqvmap/css/jqvmap.min.css" rel="stylesheet">
    <link href="../Content/css/style.css" rel="stylesheet">

    <!--flot-chart js-->
    @*<script src="../Content/vendor/flot/jquery.flot.js"></script>
    <script src="../Content/vendor/flot/jquery.flot.resize.js"></script>*@

    @*<script src="../Content/vendor/jqvmap/js/jquery.vmap.min.js"></script>
    <script src="../Content/vendor/jqvmap/js/jquery.vmap.usa.js"></script>*@
    @*<script src="../Content/vendor/jquery.counterup/jquery.counterup.min.js"></script>*@

    <!--Required vendors-->
    <script src="../Content/vendor/global/global.min.js"></script>
    @*<script src="../Scripts/js/quixnav-init.js"></script>
    <script src="../Scripts/js/custom.min.js"></script>*@

    <link rel="stylesheet" href="../Content/Site.css" />


</head>
<body>
    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <a href="/Home/Index" class="brand-logo">
                <img class="logo-abbr" src="../Content/images/logo.png" alt="">
                <img class="logo-compact" src="../Content/images/logo-text.png" alt="">
                <img class="brand-title" src="../Content/images/logo-text.png" alt="">
            </a>

            <div class="nav-control">
                <div class="hamburger">
                    <span class="line"></span><span class="line"></span><span class="line"></span>
                </div>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->
        <!--**********************************
            Header start
        ***********************************-->
        <div class="header">
            <div class="header-content">
                <nav class="navbar navbar-expand">
                    <div class="collapse navbar-collapse justify-content-between">
                        <div class="navbar-nav header-right">
                            <div class="nav-item dropdown header-profile">
                                <a class="nav-link" href="#" role="button" data-toggle="dropdown">
                                    <i class="mdi mdi-account"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="javascript:void(0);" onclick="return logoutConfirmation();" class="dropdown-item">
                                        <i class="icon-key"></i>
                                        <span class="ml-2">Logout</span>
                                    </a>

                                    <script>
                                        function logoutConfirmation() {
                                            if (confirm('Bạn có chắc chắn muốn đăng xuất?')) {
                                                 window.location.href = '@Url.Action("Logout", "TaiKhoan")';
                                            }
                                            return false;
                                        }
                                    </script>
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->
        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="quixnav">
            <div class="quixnav-scroll">
                <ul class="metismenu" id="menu">
                    <li>
                        <a class="nav-label first" href="@Url.Action("Index", "Home")" aria-expanded="false">
                            <i class="icon icon-single-04"></i><span class="nav-text">Trang chủ</span>
                        </a>
                    </li>
                    <li>
                        <a @*class="has-arrow"*@ href="@Url.Action("DSTK", "QLTK")" aria-expanded="false">
                            <i class="icon icon-app-store"></i><span class="nav-text">Quản lý tài khoản</span>
                        </a>
                    </li>
                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon icon-chart-bar-33"></i><span class="nav-text">Quản lý thông tin nhân viên</span>
                        </a>
                        <ul aria-expanded="false">
                            @*<li><a href="../QLNV/DSNV">Danh Sách</a></li>
                               <li><a href="../QLNV/ThemNV">Thêm</a></li>*@
                            <li><a href="../TTNV/DanhSachNV">Danh Sách</a></li>
                            <li><a href="../TTNV/AddNV">Thêm</a></li>
                            @*<li><a href="../TTNV/EditNV">Edit</a></li>*@
                        </ul>
                    </li>
                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon icon-world-2"></i><span class="nav-text">Quản lý chức vụ</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="~/QLCV/DanhSach">Danh Sách chức vụ</a></li>
                            <li><a href="~/QLCV/SuaCV">Sửa/Xóa</a></li>
                            <li><a href="~/QLCV/ThemCV">Thêm</a></li>
                        </ul>
                    </li>

                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon icon-plug"></i><span class="nav-text">Quản lý lương</span>
                        </a>
                        <ul aria-expanded="false">
                            <li>Lương nhân viên</li>
                        </ul>
                    </li>
                    <li>
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon icon-world-2"></i><span class="nav-text">Quản lý chấm công</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="~/ChamCong/ql_chamcong">Chấm Công</a></li>
                            <li><a href="~/ChamCong/QuanLyChamCong">Quản Lý Chấm Công</a></li>
                        </ul>
                    </li>
                </ul>
            </div>


        </div>
        <!--**********************************
            Sidebar end
        ***********************************-->
        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">
            @RenderBody()
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        <!--**********************************
            Footer start
        ***********************************-->
        <!--**********************************
            Footer end
        ***********************************-->
        <!--**********************************
           Support ticket button start
        ***********************************-->
        <!--**********************************
           Support ticket button end
        ***********************************-->


    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->
    <!--**********************************
        Scripts
    ***********************************-->
    <!--Required vendors-->
    @*<script src="../Content/vendor/global/global.min.js"></script>*@
    <script src="../Scripts/js/quixnav-init.js"></script>
    <script src="../Scripts/js/custom.min.js"></script>
    <!--Vectormap-->
    <script src="../Content/vendor/raphael/raphael.min.js"></script>
    <script src="../Content/vendor/morris/morris.min.js"></script>


    <script src="../Content/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="../Content/vendor/chart.js/Chart.bundle.min.js"></script>
    <script src="../Content/vendor/gaugeJS/dist/gauge.min.js"></script>
    <!--flot-chart js-->
    <!--<script src="../Content/vendor/flot/jquery.flot.js"></script>
    <script src="../Content/vendor/flot/jquery.flot.resize.js"></script>-->
    <!--Owl Carousel-->
    <script src="../Content/vendor/owl-carousel/js/owl.carousel.min.js"></script>

    <!--Counter Up-->
    @*<script src="../Content/vendor/jqvmap/js/jquery.vmap.min.js"></script>
        <script src="../Content/vendor/jqvmap/js/jquery.vmap.usa.js"></script>
        <script src="../Content/vendor/jquery.counterup/jquery.counterup.min.js"></script>*@
    @*<script src="../Scripts/js/dashboard/dashboard-1.js"></script>
        <script src="../Scripts/js/dashboard/dashboard-1.js"></script>*@
    @RenderSection("scripts", false)
</body>
</html>